### ISSUE TITLE
GPU Utilization and Memory buttons have stopped working

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/jupyterlab-nvdashboard#2]
It seems like at some point the `GPU Utilization` and `GPU Memory` buttons have broken. The other three buttons seem fine.

![screencap](https://user-images.githubusercontent.com/1610850/62937059-5131c780-bdc3-11e9-8ba8-4eee1adf97be.gif)

Checking the console logs in the browser and the system logs from Jupyter Lab I cannot see any error messages.

**Comment by jacobtomlinson** [comment]
@ian-r-rose any chance you would take a look at this, I'm just not sure what is going wrong?

**Comment by jacobtomlinson** [comment]
Looks like 4efbd72d caused it. I copied the fix from [here](https://github.com/dask/dask-labextension/blob/master/src/index.ts#L163-L169) which solved the problem, but also seemed to introduce this.

**Comment by ian-r-rose** [comment]
I wonder if it's the same bug as the one fixed [here](https://github.com/dask/dask-labextension/pull/74)? I still haven't really figured out the root cause of it -- I have some suspicions of an upstream bug.

**Comment by jacobtomlinson** [comment]
Yep that did it thanks!

**Comment by ian-r-rose** [comment]
Great! I view that fix as more of a band-aid -- but it should allow us to move forward.

**Comment by jacobtomlinson** [comment]
Any chance you could give me a pointer in #3 in this repo while you're here. My grepping about in the dask lab extension isn't going so well.
