### ISSUE TITLE
Set subwindow favicon

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/jupyterlab-nvdashboard#3]
The window panes that are opened to show the dashboards do not have a favicon. I would be good to set this to the same logo as the sidebar is using.

This is already done in the Dask extension.

![image](https://user-images.githubusercontent.com/1610850/62936895-dbc5f700-bdc2-11e9-917e-90900ed58531.png)

**Comment by ian-r-rose** [comment]
You will want to deploy some CSS with the icon logo as a background image, and then do something along these lines: https://github.com/ian-r-rose/dask-labextension/blob/5b67f064f83757c887d2dea38e87a788a4ffebe5/src/index.ts#L154-L156

**Comment by jacobtomlinson** [comment]
Yeah I've [already done that](https://github.com/jacobtomlinson/jupyterlab-nvdashboard/blob/master/src/index.ts#L35-L37) for the sidebar, see the little GPU icon from Material Design Icons.

What I can't figure out is how to get the tabs to have that icon too.

![image](https://user-images.githubusercontent.com/1610850/63006536-a8dd3b00-be76-11e9-8656-8c317d496e61.png)

**Comment by ian-r-rose** [comment]
Ah, my mistake, I meant to link to the main area widget part, which looks very similar to the sidebar part: https://github.com/ian-r-rose/dask-labextension/blob/5b67f064f83757c887d2dea38e87a788a4ffebe5/src/index.ts#L344-L346

**Comment by jacobtomlinson** [comment]
Awesome thanks!
