### ISSUE TITLE
Missing git tags for 0.1.1 and 0.1.2

### ISSUE THREAD

**Issue by jakirkham** [jacobtomlinson/jupyterlab-nvdashboard#5]
Noticed there were a few PyPI releases where there are not git tags on the repo. Would it be possible to add these?

Also was there a 0.1.4 release or did that get skipped over?

**Comment by jacobtomlinson** [comment]
Was having some initial issues with releasing, `0.1.1`, `0.1.2` and `0.1.4` were all broken. Things should be fine now with `0.1.5`.

I was planning on removing the broken releases completely from PyPI and NPM and considering them skipped over. Do you see any issues with that?

**Comment by jakirkham** [comment]
Mainly it can be useful for people trying different releases to identify what change(s) may have fixed or caused an issue.

Figured these tags were things you already had locally. So it would be trivial to push them. If that’s not the case, I wouldn’t worry about it (unless this comes up for another reason).

While I certainly understand the desire to delete older releases that caused problems, most packagers would not recommend this strategy. It simply makes it harder to figure out what caused an issue and how to avoid it in the future. Would recommend leaving them and just encourage people to upgrade to the latest version.

**Comment by jacobtomlinson** [comment]
That makes sense.

I don't have tags locally as I was tying myself in knots locally with some of the tooling. I've got a good flow for this now with `jlpm` and Travis CI now though, so it shouldn't happen again.

**Comment by jakirkham** [comment]
FWIW I’ve found versioneer to be pretty handy when handling versioning as it translates git tags into package versions with ease. This is more Python-based. So there may be a little bit of work to connect this with JavaScript. There are a few other tools along these lines. Happy to discuss more if this is of interest.

**Comment by jacobtomlinson** [comment]
Yup, love versioneer. 

The node package is taking the lead on the version info (`setup.py`imports the `package.json` file from the Node package). As node uses a static JSON file rather than a script like `setup.py` I would imagine it would take a bit of `sed` magic or similar to update it.

Would be neat to look into this.
